GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/6060984ba044c839446a83f

###
DELETE http://localhost:3001/api/persons/4

###
DELETE http://localhost:3001/api/persons/6060984ba044c839446a83f1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Luna Lovegood",
    "number": "384-387342"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Luna Lovegood",
    "number": "384232"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "384-387342"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Ja",
    "number": "23232-23222222"
}

###
PUT http://localhost:3001/api/persons/6060984ba044c839446a83f1
Content-Type: application/json

{
    "name": "Jack Nicholson",
    "number": "23232-232"
}