GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Luna Lovegood",
    "number": "384-387342"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Luna Lovegood",
    "number": "384232"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "384-387342"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ron Weasley",
    "number": "4325325-23423"
}